[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
    "kayak_components",
    "kayak_core",
    "kayak_render_macros",
    "kayak_font",
]

[dependencies]
kayak_components = { path = "kayak_components" }
kayak_core = { path = "kayak_core" }

[dev-dependencies]
bevy = { git = "https://github.com/StarArawn/bevy", rev = "146ddbe5f839d5d635fe350a535155231d4050c2" }
bevy_kayak_ui = { path = "bevy_kayak_ui" }
