[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
    "kayak_components",
    "kayak_core",
    "kayak_render_macros",
    "kayak_font",
]

[dependencies]
kayak_components = { path = "kayak_components" }
kayak_core = { path = "kayak_core" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "38c7d5eb9e81ab8e1aec03673599b25a9aa0c69c" }
bevy_kayak_ui = { path = "bevy_kayak_ui" }
