[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
    "bevy_kayak_ui",
    "kayak_widgets",
    "kayak_core",
    "kayak_render_macros",
    "kayak_font",
]

[features]
default = ["bevy_renderer"]
bevy_renderer = ["bevy_kayak_ui", "kayak_font"]

[dependencies]
kayak_widgets = { path = "kayak_widgets" }
kayak_core = { path = "kayak_core" }
bevy_kayak_ui = { path = "bevy_kayak_ui", optional = true }
kayak_font = { path = "kayak_font", optional = true }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "38c7d5eb9e81ab8e1aec03673599b25a9aa0c69c" }
