[package]
name = "kayak_font"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
bevy = { version = "0.6.0" }
bytemuck = "1.7.2"
serde = "1.0"
serde_json = "1.0"
serde_path_to_error = "0.1"
