[package]
name = "bevy_kayak_ui"
version = "0.0.1"
edition = "2021"

[dependencies]
bytemuck = "1.7.2"
bevy = { git = "https://github.com/bevyengine/bevy", rev = "38c7d5eb9e81ab8e1aec03673599b25a9aa0c69c" }
kayak_core = { path = "../kayak_core" }
kayak_render_macros = { path = "../kayak_render_macros" }
kayak_font = { path = "../kayak_font" }
#kayak_font = { path = "../kayak_font" }
crevice = { git = "https://github.com/bevyengine/bevy", rev = "38c7d5eb9e81ab8e1aec03673599b25a9aa0c69c" }
serde = "1.0"
serde_json = "1.0"
serde_path_to_error = "0.1"
